name: Docker Image CI

on:
  workflow_run:
    workflows: [".NET"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    
    - 
      name: Checkout the repo
      uses: actions/checkout@v4

    - 
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/div2005/orchideasalon           
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./orchideasalon
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
